# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 55dbc7a69784056c92522b82961d06c6a2a041f2086398cde01385a88eaf0d1cb8be01e9238e9a2f2c09762288ca4be540cb5a2c62f9ce4f10a6d5992b3a02e4

test:
  secret_key_base: 311f7e1ef6190fcb0ecac6f469d8f525325bb0cec11b68ba21c163f367dd198994ad2f7ea77cfcd61861257aeddfcb0a76778fee13ece5e902a9ae4940ab7ac1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
